#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

required=(
  "CONTRIBUTING.md"
  "SECURITY.md"
  "CODE_OF_CONDUCT.md"
  "CHANGELOG.md"
  "ROADMAP.md"
)

for file in "${required[@]}"; do
  if [[ ! -s "$ROOT_DIR/$file" ]]; then
    echo "missing required repository document: $file" >&2
    exit 1
  fi
done

grep -q "clean-room" "$ROOT_DIR/CONTRIBUTING.md"
grep -q "MATLAB" "$ROOT_DIR/CONTRIBUTING.md"
grep -q "private data" "$ROOT_DIR/SECURITY.md"
grep -q "v0.1.5" "$ROOT_DIR/CHANGELOG.md"
grep -q "## Preview" "$ROOT_DIR/README.md"
grep -q "## Install" "$ROOT_DIR/README.md"
grep -q "## CLI" "$ROOT_DIR/README.md"
grep -q "## Scheme Coverage" "$ROOT_DIR/README.md"
grep -q "## Provenance" "$ROOT_DIR/README.md"
grep -q "does not depend on private archives" "$ROOT_DIR/README.md"
grep -q "working MATLAB command line executable" "$ROOT_DIR/README.md"
grep -q "All previews below are generated from bundled synthetic data" "$ROOT_DIR/README.md"
grep -q -- "--scheme-info-json line_trend" "$ROOT_DIR/README.md"
grep -q -- "--inspect-data" "$ROOT_DIR/README.md"
grep -q -- "--plan-only" "$ROOT_DIR/README.md"
grep -q -- "--smoke-test" "$ROOT_DIR/README.md"
grep -q "scripts/build_automation_manifest.py" "$ROOT_DIR/README.md"
grep -q "scripts/build_task_manifest.py" "$ROOT_DIR/README.md"
grep -q "docs/gallery/index.md" "$ROOT_DIR/README.md"
grep -q "docs/gallery/provenance.md" "$ROOT_DIR/README.md"
grep -q "docs/chart-selection-guide.md" "$ROOT_DIR/README.md"
grep -q "docs/figure-quality-checklist.md" "$ROOT_DIR/README.md"
grep -q "docs/automation-manifest.md" "$ROOT_DIR/README.md"
grep -q "docs/500-task-board.md" "$ROOT_DIR/README.md"
grep -q "# First 5 Minutes" "$ROOT_DIR/docs/first-five-minutes.md"
grep -q "## 1. Check The Catalog Without MATLAB" "$ROOT_DIR/docs/first-five-minutes.md"
grep -q "## 4. Render Into A Scratch Directory" "$ROOT_DIR/docs/first-five-minutes.md"
grep -q "SFT_OUTPUT_DIR is not used by this repository" "$ROOT_DIR/docs/first-five-minutes.md"
grep -q "# First Render Walkthrough" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "## 1. Try Metadata First" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "Use these commands before configuring MATLAB" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q -- "--scheme-info-json line_trend" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q -- "MP_MATLAB_TIMEOUT_SECONDS=0" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q -- "--inspect-data" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q -- "--plan-only" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "render_report.md" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "rejects unknown format names before MATLAB starts" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "matlab-plotting-skill/issues/11" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "Redact private paths" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "Copy this template when reporting a first-use result" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "Command sequence:" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "Private details redacted: yes/no" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "The public workflow does not render figures with MATLAB" "$ROOT_DIR/docs/ci-coverage.md"
grep -q "MATLAB release gate" "$ROOT_DIR/docs/ci-coverage.md"
grep -q "# Maintenance Cadence" "$ROOT_DIR/docs/maintenance-cadence.md"
grep -q "## Release History Boundary" "$ROOT_DIR/docs/maintenance-cadence.md"
grep -q "not the normal maintenance rhythm" "$ROOT_DIR/docs/maintenance-cadence.md"
grep -q "Do not tag a release only because one task-board row moved to" "$ROOT_DIR/docs/maintenance-cadence.md"
grep -q "Review new issues and first-use feedback weekly" "$ROOT_DIR/docs/maintenance-cadence.md"
grep -q "# Roadmap" "$ROOT_DIR/ROADMAP.md"
grep -q 'Current public line: `v0.1.x`' "$ROOT_DIR/ROADMAP.md"
grep -q "No artificial stars, forks, usage claims, or download claims" "$ROOT_DIR/ROADMAP.md"
grep -q "No release tag for every checklist row" "$ROOT_DIR/ROADMAP.md"
grep -q "# Ecosystem Status" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "matlab-scientific-figures#9" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "matlab-figure-ci#1" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "claim broad adoption" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "# Scheme Readiness" "$ROOT_DIR/docs/scheme-readiness.md"
grep -q "| gallery-backed | 9 |" "$ROOT_DIR/docs/scheme-readiness.md"
grep -q "## Stable First-Use Schemes" "$ROOT_DIR/docs/scheme-readiness.md"

echo "repository docs test passed."
