#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

required=(
  "CONTRIBUTING.md"
  "SECURITY.md"
  "CODE_OF_CONDUCT.md"
  "CHANGELOG.md"
  "ROADMAP.md"
)

for file in "${required[@]}"; do
  if [[ ! -s "$ROOT_DIR/$file" ]]; then
    echo "missing required repository document: $file" >&2
    exit 1
  fi
done

grep -q "clean-room" "$ROOT_DIR/CONTRIBUTING.md"
grep -q "MATLAB" "$ROOT_DIR/CONTRIBUTING.md"
grep -q "private data" "$ROOT_DIR/SECURITY.md"
grep -q "v0.1.5" "$ROOT_DIR/CHANGELOG.md"
grep -q "Works without MATLAB" "$ROOT_DIR/README.md"
grep -q "简体中文" "$ROOT_DIR/README.md"
grep -q "# MATLAB Plotting Skill" "$ROOT_DIR/README.zh-CN.md"
grep -q "前 5 分钟" "$ROOT_DIR/README.zh-CN.md"
grep -q "方案覆盖" "$ROOT_DIR/README.zh-CN.md"
grep -q "发布状态" "$ROOT_DIR/README.zh-CN.md"
grep -q "v0.1.x" "$ROOT_DIR/README.zh-CN.md"
grep -q "不要直接上传私有数据文件" "$ROOT_DIR/README.zh-CN.md"
grep -q "不代表每完成一行就发布一个版本" "$ROOT_DIR/README.zh-CN.md"
grep -q "来源与安全" "$ROOT_DIR/README.zh-CN.md"
grep -q "选择算法和解释字段" "$ROOT_DIR/README.zh-CN.md"
grep -q "Requires MATLAB" "$ROOT_DIR/README.md"
grep -q "Try Metadata First" "$ROOT_DIR/README.md"
grep -q "before configuring MATLAB" "$ROOT_DIR/README.md"
grep -q -- "--scheme-info-json line_trend" "$ROOT_DIR/README.md"
grep -q -- "MP_MATLAB_TIMEOUT_SECONDS=0" "$ROOT_DIR/README.md"
grep -q "Windows Git Bash" "$ROOT_DIR/README.md"
grep -q "matlab.exe" "$ROOT_DIR/README.md"
grep -q 'Use `--scheme` to bypass planning' "$ROOT_DIR/README.md"
grep -q "RoleHint" "$ROOT_DIR/README.md"
grep -q "NextCommandHint" "$ROOT_DIR/README.md"
grep -q "## First 5 Minutes" "$ROOT_DIR/README.md"
grep -q "1. Check the catalog without MATLAB." "$ROOT_DIR/README.md"
grep -q "2. Confirm MATLAB is callable." "$ROOT_DIR/README.md"
grep -q "3. Inspect and plan with the bundled CSV." "$ROOT_DIR/README.md"
grep -q "4. Render into a scratch directory." "$ROOT_DIR/README.md"
grep -q "SFT_OUTPUT_DIR is not used by this repository" "$ROOT_DIR/README.md"
grep -q "docs/first-five-minutes.md" "$ROOT_DIR/README.md"
grep -q "# First 5 Minutes" "$ROOT_DIR/docs/first-five-minutes.md"
grep -q "## 1. Check The Catalog Without MATLAB" "$ROOT_DIR/docs/first-five-minutes.md"
grep -q -- "--scheme-info line_trend --status" "$ROOT_DIR/docs/first-five-minutes.md"
grep -q -- "--explain --data examples/data/time_series.csv" "$ROOT_DIR/docs/first-five-minutes.md"
grep -q "## 4. Use More Bundled Fixtures" "$ROOT_DIR/docs/first-five-minutes.md"
grep -q "## 5. Render Into A Scratch Directory" "$ROOT_DIR/docs/first-five-minutes.md"
grep -q "SFT_OUTPUT_DIR is not used by this repository" "$ROOT_DIR/docs/first-five-minutes.md"
grep -q "Invalid entries fail before MATLAB starts" "$ROOT_DIR/README.md"
grep -q -- "--list-schemes" "$ROOT_DIR/README.md"
grep -q -- "--plan-only" "$ROOT_DIR/README.md"
grep -q "docs/ci-coverage.md" "$ROOT_DIR/README.md"
grep -q "docs/install-targets.md" "$ROOT_DIR/README.md"
grep -q "docs/scheme-readiness.md" "$ROOT_DIR/README.md"
grep -q "docs/first-render-walkthrough.md" "$ROOT_DIR/README.md"
grep -q "docs/selection-algorithm.md" "$ROOT_DIR/README.md"
grep -q "docs/activation-contract.md" "$ROOT_DIR/README.md"
grep -q "docs/local-resource-intake.md" "$ROOT_DIR/README.md"
grep -q "docs/cli-output-contract.md" "$ROOT_DIR/README.md"
grep -q "docs/private-data-handling.md" "$ROOT_DIR/README.md"
grep -q "docs/ecosystem-status.md" "$ROOT_DIR/README.md"
grep -q "docs/maintenance-cadence.md" "$ROOT_DIR/README.md"
grep -q "ROADMAP.md" "$ROOT_DIR/README.md"
grep -q "## Release Status" "$ROOT_DIR/README.md"
grep -q "Early bootstrap tags were intentionally" "$ROOT_DIR/README.md"
grep -q "The catalog contains 50 plotting schemes" "$ROOT_DIR/README.md"
grep -q "gallery-backed schemes listed in" "$ROOT_DIR/README.md"
grep -q "most stable first-use path" "$ROOT_DIR/README.md"
grep -q "Cataloged-only schemes are" "$ROOT_DIR/README.md"
grep -q "long-horizon scheme backlog" "$ROOT_DIR/README.md"
grep -q "without turning every task into a release" "$ROOT_DIR/README.md"
grep -q "first-use feedback issue template" "$ROOT_DIR/README.md"
grep -q "collect_first_use_feedback.sh --out" "$ROOT_DIR/README.md"
grep -q "collect_first_use_feedback.sh --out" "$ROOT_DIR/README.zh-CN.md"
grep -q "docs/local-resource-intake.md" "$ROOT_DIR/README.zh-CN.md"
grep -q "docs/activation-contract.md" "$ROOT_DIR/README.zh-CN.md"
grep -q "first-render-walkthrough.zh-CN.md" "$ROOT_DIR/README.zh-CN.md"
grep -q "Windows Git Bash" "$ROOT_DIR/README.zh-CN.md"
grep -q "matlab.exe" "$ROOT_DIR/README.zh-CN.md"
grep -q '使用 `--scheme` 会跳过自动规划' "$ROOT_DIR/README.zh-CN.md"
grep -q "RoleHint" "$ROOT_DIR/README.zh-CN.md"
grep -q "NextCommandHint" "$ROOT_DIR/README.zh-CN.md"
grep -q "activation:" "$ROOT_DIR/skills/matlab-plotting-skill/SKILL.md"
grep -q "version: 1" "$ROOT_DIR/skills/matlab-plotting-skill/SKILL.md"
grep -q "prefers:" "$ROOT_DIR/skills/matlab-plotting-skill/SKILL.md"
grep -q "deprioritises:" "$ROOT_DIR/skills/matlab-plotting-skill/SKILL.md"
grep -q "MATLAB_BIN" "$ROOT_DIR/skills/matlab-plotting-skill/SKILL.md"
grep -q "matplotlib" "$ROOT_DIR/skills/matlab-plotting-skill/SKILL.md"
grep -q "local-resource-intake.md" "$ROOT_DIR/skills/matlab-plotting-skill/SKILL.md"
grep -q "# Local Resource Intake" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "clean-room task" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "Nature/Science" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q ".opju" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q ".mat" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "synthetic data" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "Current Backlog Signals" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "fft_spectrum" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "impedance_locus" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "calibration_curve" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "power_quality_trend" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "workflow_diagram" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "A chart name is allowed to become a task" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "## Promotion Checklist" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "deterministic synthetic data" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "If any item is missing" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "Private Prototype Library Review" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "216 plotting ideas" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "239-template map" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "60 palette families" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "Go-side helper experiments" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "Palette And Origin Boundary" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "The skill should not import the prototype functions" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "private folder the user cannot inspect" "$ROOT_DIR/README.md"
grep -q "私人文件夹" "$ROOT_DIR/README.zh-CN.md"
grep -q "Recent local review points toward signal-processing plots" "$ROOT_DIR/docs/500-task-plan.md"
grep -q "Treat that as" "$ROOT_DIR/docs/500-task-plan.md"
grep -q "a map, not as an import queue" "$ROOT_DIR/docs/500-task-plan.md"
grep -q "239 template ideas" "$ROOT_DIR/docs/500-task-plan.md"
grep -q "power/energy" "$ROOT_DIR/docs/500-task-plan.md"
grep -q "not usage claims" "$ROOT_DIR/docs/local-resource-intake.md"
grep -q "write it as a public" "$ROOT_DIR/skills/matlab-plotting-skill/SKILL.md"
grep -q '"power", "energy", "harmonic"' "$ROOT_DIR/skills/matlab-plotting-skill/SKILL.md"
grep -q "# Activation Contract" "$ROOT_DIR/docs/activation-contract.md"
grep -q "activation.version" "$ROOT_DIR/docs/activation-contract.md"
grep -q "does not guarantee" "$ROOT_DIR/docs/activation-contract.md"
grep -q "metadata-only" "$ROOT_DIR/docs/activation-contract.md"
grep -q "MATLAB-required" "$ROOT_DIR/docs/activation-contract.md"
grep -q "mpSelectScheme" "$ROOT_DIR/docs/activation-contract.md"
grep -q "# First Render Walkthrough" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "## 1. Try Metadata First" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "Use these commands before configuring MATLAB" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q -- "--scheme-info-json line_trend" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q -- "--scheme-info line_trend --status" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q -- "--explain" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q -- "MP_MATLAB_TIMEOUT_SECONDS=0" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "Windows Git Bash" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "matlab.exe" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q 'Use `--scheme` to bypass planning' "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q -- "--inspect-data" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q -- "--plan-only" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "render_report.md" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "rejects unknown format names before MATLAB starts" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "matlab-plotting-skill/issues/11" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "Redact private paths" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "collect_first_use_feedback.sh" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "Copy this template when reporting a first-use result" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "Command sequence:" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "Private details redacted: yes/no" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "docs/private-data-handling.md" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "# 第一次渲染指南" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q "## 1. 先看元数据" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q -- "--scheme-info-json line_trend" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q "MP_MATLAB_TIMEOUT_SECONDS=0" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q "Windows Git Bash" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q "matlab.exe" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q '使用 `--scheme` 会跳过自动规划' "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q -- "--inspect-data" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q -- "--plan-only" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q "render_report.md" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q "matlab-plotting-skill/issues/11" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q "collect_first_use_feedback.sh" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q "Private details redacted: yes/no" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q "The public workflow does not render figures with MATLAB" "$ROOT_DIR/docs/ci-coverage.md"
grep -q "MATLAB release gate" "$ROOT_DIR/docs/ci-coverage.md"
grep -q "# Selection Algorithm" "$ROOT_DIR/docs/selection-algorithm.md"
grep -q -- "--explain" "$ROOT_DIR/docs/selection-algorithm.md"
grep -q "ScoreSnapshot" "$ROOT_DIR/docs/selection-algorithm.md"
grep -q "Warnings" "$ROOT_DIR/docs/selection-algorithm.md"
grep -q "Panel/layout goal may be trivial" "$ROOT_DIR/docs/selection-algorithm.md"
grep -q "Outlier goal needs explicit outlier evidence" "$ROOT_DIR/docs/selection-algorithm.md"
grep -q "statistical model" "$ROOT_DIR/docs/selection-algorithm.md"
grep -q "# CLI Output Contract" "$ROOT_DIR/docs/cli-output-contract.md"
grep -q -- "--scheme-info-json <name> --status" "$ROOT_DIR/docs/cli-output-contract.md"
grep -q "RoleHint" "$ROOT_DIR/docs/cli-output-contract.md"
grep -q "NextCommandHint" "$ROOT_DIR/docs/cli-output-contract.md"
grep -q "warnings" "$ROOT_DIR/docs/cli-output-contract.md"
grep -q "does not include absolute local paths" "$ROOT_DIR/docs/cli-output-contract.md"
grep -q "RoleHint" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "NextCommandHint" "$ROOT_DIR/docs/first-render-walkthrough.md"
grep -q "RoleHint" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q "NextCommandHint" "$ROOT_DIR/docs/first-render-walkthrough.zh-CN.md"
grep -q "# Private Data Handling" "$ROOT_DIR/docs/private-data-handling.md"
grep -q "Do Not Share" "$ROOT_DIR/docs/private-data-handling.md"
grep -q "# Maintenance Cadence" "$ROOT_DIR/docs/maintenance-cadence.md"
grep -q "## Release History Boundary" "$ROOT_DIR/docs/maintenance-cadence.md"
grep -q "not the normal maintenance rhythm" "$ROOT_DIR/docs/maintenance-cadence.md"
grep -q "Do not tag a release only because one task-board row moved to" "$ROOT_DIR/docs/maintenance-cadence.md"
grep -q "Review new issues and first-use feedback weekly" "$ROOT_DIR/docs/maintenance-cadence.md"
grep -q "# Roadmap" "$ROOT_DIR/ROADMAP.md"
grep -q 'Current public line: `v0.1.x`' "$ROOT_DIR/ROADMAP.md"
grep -q "No artificial stars, forks, usage claims, or download claims" "$ROOT_DIR/ROADMAP.md"
grep -q "No release tag for every checklist row" "$ROOT_DIR/ROADMAP.md"
grep -q "# Install Targets" "$ROOT_DIR/docs/install-targets.md"
grep -q -- "--target claude-code" "$ROOT_DIR/docs/install-targets.md"
grep -q -- "--target dir --path ./skills" "$ROOT_DIR/docs/install-targets.md"
grep -q "The installer only places the skill folder on disk" "$ROOT_DIR/docs/install-targets.md"
grep -q "# Ecosystem Status" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "matlab-scientific-figures#9" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "matlab-figure-ci#1" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "first-render-walkthrough.zh-CN.md" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "matlab-scientific-figures#31" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "visible fork intake" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "open issue/PR triage" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "required GitHub Projects scopes" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "matlab-figure-ci.*v2.5.0" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "companion adoption report" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "first_use_doctor.md/json" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "docs/first-use-doctor.md" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "doctor report summary" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "## Handoff Contract" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "Producer artifact" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "Next consumer" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "render_report.md and render_report.json" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "mfigci-report.md and .mfigci-results.json" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "Do not move private datasets" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "handoff contract" "$ROOT_DIR/README.md"
grep -q "claim broad adoption" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "## Maintainer Evidence Packet" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "review packet" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "application packet" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "workflow run URL" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "mfigci report --style evidence --output mfigci-evidence.md" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "available on matlab-figure-ci main after v2.5.0" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "render_report.md/json" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "mfigci-report.md" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "redacted issue or PR link" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "not an approval argument" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "agent-facing layer for the MATLAB plotting ecosystem" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "Do not include private datasets" "$ROOT_DIR/docs/ecosystem-status.md"
grep -q "# Scheme Readiness" "$ROOT_DIR/docs/scheme-readiness.md"
grep -q "| gallery-backed | 11 |" "$ROOT_DIR/docs/scheme-readiness.md"
grep -q "| render path started | 1 |" "$ROOT_DIR/docs/scheme-readiness.md"
grep -q '| `contour_scatter` | Relationship | gallery-backed |' "$ROOT_DIR/docs/scheme-readiness.md"
grep -q '| `regression_scatter` | Relationship | gallery-backed |' "$ROOT_DIR/docs/scheme-readiness.md"
grep -q '| `bubble_scatter` | Relationship | render path started |' "$ROOT_DIR/docs/scheme-readiness.md"
grep -q "## Stable First-Use Schemes" "$ROOT_DIR/docs/scheme-readiness.md"
grep -q "Windows Git Bash" "$ROOT_DIR/skills/matlab-plotting-skill/references/matlab-cli.md"
grep -q "matlab.exe" "$ROOT_DIR/skills/matlab-plotting-skill/references/matlab-cli.md"
grep -q "bypasses automatic planning" "$ROOT_DIR/skills/matlab-plotting-skill/references/matlab-cli.md"

echo "repository docs test passed."
