#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKFLOW="$ROOT_DIR/.github/workflows/quality.yml"

if [[ ! -s "$WORKFLOW" ]]; then
  echo "missing quality workflow" >&2
  exit 1
fi

grep -q "scripts/build_automation_manifest.py" "$WORKFLOW"
grep -q "actions/checkout@v6" "$WORKFLOW"
grep -q "actions/upload-artifact@v5" "$WORKFLOW"
grep -q "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24" "$WORKFLOW"
grep -Fq "find scripts -type d -name '__pycache__' -prune -exec rm -rf {} +" "$WORKFLOW"
grep -q "bash -n scripts/doctor.sh" "$WORKFLOW"
grep -q "bash -n tests/test_doctor.sh" "$WORKFLOW"
grep -q "bash -n tests/test_doctor_docs.sh" "$WORKFLOW"
grep -q "tests/test_doctor.sh" "$WORKFLOW"
grep -q "tests/test_doctor_docs.sh" "$WORKFLOW"
grep -q "tests/test_check_privacy.sh" "$WORKFLOW"
grep -q "tests/test_collect_first_use_feedback.sh" "$WORKFLOW"
grep -q "scripts/collect_first_use_feedback.sh" "$WORKFLOW"
grep -q "tests/test_cli_output_contract.sh" "$WORKFLOW"
grep -q "tests/test_first_five_minutes_fixtures.sh" "$WORKFLOW"
grep -q "tests/test_scheme_info.sh" "$WORKFLOW"
grep -q "tests/test_automation_manifest.sh" "$WORKFLOW"
grep -q "tests/test_ci_workflow.sh" "$WORKFLOW"
grep -q "tests/test_task_manifest.sh" "$WORKFLOW"
grep -q "tests/test_task_manifest_filter.sh" "$WORKFLOW"
grep -q "tests/test_task_manifest_status.sh" "$WORKFLOW"
grep -q "tests/test_scheme_readiness.sh" "$WORKFLOW"
grep -q "tests/test_scheme_readiness_fresh.sh" "$WORKFLOW"
grep -q "tests/test_docs_voice.sh" "$WORKFLOW"
grep -q "bash -n tests/test_scheme_readiness.sh" "$WORKFLOW"
grep -q "bash -n tests/test_scheme_readiness_fresh.sh" "$WORKFLOW"
grep -q "bash -n tests/test_docs_voice.sh" "$WORKFLOW"
grep -q "tests/test_docs_500_task_board.sh" "$WORKFLOW"
grep -q "tests/test_line_trend_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_multi_line_comparison_catalog.sh" "$WORKFLOW"
grep -q "tests/test_multi_line_comparison_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_confidence_band_catalog.sh" "$WORKFLOW"
grep -q "tests/test_zoomed_inset_line_catalog.sh" "$WORKFLOW"
grep -q "tests/test_positive_negative_area_catalog.sh" "$WORKFLOW"
grep -q "tests/test_segmented_line_catalog.sh" "$WORKFLOW"
grep -q "tests/test_scatter_relationship_catalog.sh" "$WORKFLOW"
grep -q "tests/test_grouped_scatter_catalog.sh" "$WORKFLOW"
grep -q "tests/test_density_scatter_catalog.sh" "$WORKFLOW"
grep -q "tests/test_contour_scatter_catalog.sh" "$WORKFLOW"
grep -q "tests/test_regression_scatter_catalog.sh" "$WORKFLOW"
grep -q "tests/test_bubble_scatter_catalog.sh" "$WORKFLOW"
grep -q "tests/test_confidence_band_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_zoomed_inset_line_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_positive_negative_area_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_segmented_line_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_scatter_relationship_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_grouped_scatter_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_density_scatter_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_contour_scatter_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_regression_scatter_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_bubble_scatter_data_contract.sh" "$WORKFLOW"
grep -q "tests/test_line_trend_gallery.sh" "$WORKFLOW"
grep -q "tests/test_multi_line_comparison_gallery.sh" "$WORKFLOW"
grep -q "tests/test_confidence_band_gallery.sh" "$WORKFLOW"
grep -q "tests/test_zoomed_inset_line_gallery.sh" "$WORKFLOW"
grep -q "tests/test_positive_negative_area_gallery.sh" "$WORKFLOW"
grep -q "tests/test_segmented_line_gallery.sh" "$WORKFLOW"
grep -q "tests/test_scatter_relationship_gallery.sh" "$WORKFLOW"
grep -q "tests/test_grouped_scatter_gallery.sh" "$WORKFLOW"
grep -q "tests/test_density_scatter_gallery.sh" "$WORKFLOW"
grep -q "tests/test_contour_scatter_gallery.sh" "$WORKFLOW"
grep -q "tests/test_regression_scatter_gallery.sh" "$WORKFLOW"
grep -q "tests/test_multi_line_comparison_safety.sh" "$WORKFLOW"
grep -q "tests/test_confidence_band_safety.sh" "$WORKFLOW"
grep -q "tests/test_zoomed_inset_line_safety.sh" "$WORKFLOW"
grep -q "tests/test_positive_negative_area_safety.sh" "$WORKFLOW"
grep -q "tests/test_segmented_line_safety.sh" "$WORKFLOW"
grep -q "tests/test_scatter_relationship_safety.sh" "$WORKFLOW"
grep -q "tests/test_grouped_scatter_safety.sh" "$WORKFLOW"
grep -q "tests/test_density_scatter_safety.sh" "$WORKFLOW"
grep -q "tests/test_contour_scatter_safety.sh" "$WORKFLOW"
grep -q "tests/test_regression_scatter_safety.sh" "$WORKFLOW"
grep -q "tests/test_gallery_provenance.sh" "$WORKFLOW"
grep -q "automation-manifest.json" "$WORKFLOW"
grep -q "task-manifest.json" "$WORKFLOW"
grep -q "task-board.md" "$WORKFLOW"
grep -q "docs/task-status.json" "$WORKFLOW"
grep -q "actions/upload-artifact" "$WORKFLOW"
grep -q "Clean generated Python cache" "$WORKFLOW"
grep -Fq "find . -type d -name '__pycache__' -not -path './.git/*' -prune -exec rm -rf {} +" "$WORKFLOW"

echo "CI workflow test passed."
